name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare dependencies
      run: |
        choco install vulkan-sdk -y
        RefreshEnv
        vcpkg install glfw3:x64-windows glm:x64-windows vulkan:x64-windows
    - name: Build Visual Studio solution
      working-directory: ${{ github.workspace }}
      run: '& "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" .\vs\GeoWars.sln'

